spring:
  datasource:
    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S11P22A106?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S11P22A106@stg-yswa-kr-practice-db-master
    password: abuba106
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 465
    username: 106hexagon@gmail.com
    password: kpmk utrt asla pelt
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


#ec2 주소
app:
  email:
    verification-url: http://localhost:8080/api/v1/auth/verify-email

  jpa:
    hibernate:
      ddl-auto: update


  servlet:
    multipart:
      enabled: true
      max-request-size: 300MB
      max-file-size: 50MB

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    bucket-name: hexagon-abuba
    region: ap-northeast-2


