spring:
  datasource:
    url: jdbc:mysql://localhost:3306/abuba
    username: abuba
    password: abuba
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      enabled: true
      max-request-size: 300MB
      max-file-size: 50MB

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    bucket-name: hexagon-abuba
    region: ap-northeast-2


app:
  email:
    verification-url: http://localhost:8080/api/v1/auth/verify-email

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: 106hexagon@gmail.com
#    password: wuya kvvf iebm ouko
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true